name: pr_ai
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9.16
  - numpy=1.26.4
  - pandas=2.1.4
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - tqdm=4.66.5
  - tensorboardX=2.6.2.2
  - scikit-learn=1.5.2
  - optuna=4.0.0
  - pexpect=4.9.0
  - matplotlib=3.7.1
  - seaborn=0.13.1
