name: pr_ai
channels:
  - defaults
dependencies:
  - python=3.10.12
  - numpy=1.26.4
  - pandas=2.1.4
  - pytorch=2.4.1+cu121
  - tqdm=4.66.5
  - tensorboardX=2.6.2.2
  - scikit-learn=1.5.2
  - argparse=1.1
  - optuna=4.0.0
  - json=2.0.9
  - pexpect=4.9.0
  - re=2.2.1
  - csv=1.0
  - matplotlib=3.7.1
  - seaborn=0.13.1